### PR TITLE
Expose the default-client and default headers

### PR DESCRIPTION
**Pull request by lispyclouds**
Draft PR, gathering feedback. Still WIP.

### CODE REVIEW

**Comment by lispyclouds** [comment]
Implemented the default header merging like what i understand curl does. Not sure if that's the best way. Maybe the implementation could be more generic?

**Comment by borkdude** [comment]
@lispyclouds I made a PR myself here: https://github.com/babashka/http-client/pull/9

My intention wasn't to expose the default client itself, but only the options to construct it. Re-using the default client over multiple requests has the benefit of re-using connections if you make multiple requests.

I also added the option to pass `:request` options to `client` so it remembers those options whenever you make a request. I used that in the construction of the default client.

Let me know if you spot anything weird.

**Comment by lispyclouds** [comment]
yep, looks much better! closing mine.

**Comment by borkdude** [comment]
Thanks, your PR helped the hammock process even if it wasn't merged ;)

**Comment by lispyclouds** [comment]
yeah it was a lot of fun for me too! avoiding the deep merge is probably a better choice.

**Pull request closed without merging**
