### PR TITLE
[feat] add default user-agent

### PR DESCRIPTION
**Pull request by lispyclouds**
Modelled it after [curl](https://everything.curl.dev/http/requests/user-agent). Should a `resources/BABASHKA_HTTP_CLIENT_VERSION` be used?

### CODE REVIEW

**Comment by borkdude** [comment]
The version is stored in `deps.edn` but I guess that's not part of the deployed stuff.

Perhaps we can add `babashka.http-client.impl.version.clj` with `(ns ..) (def version ...)` and make a script to refresh this by reading the `deps.edn`?

**Comment by borkdude** [comment]
I'll take care of that version.clj thing.

**Comment by borkdude** [comment]
Added the version.clj now

**Comment by lispyclouds** [comment]
incorporating it now

**Comment by borkdude** [comment]
Can you maybe not use force push? :)

**Comment by lispyclouds** [comment]
> Can you maybe not use force push?

Yeah that was the main rebase. Will merge next time.

**Comment by borkdude** [comment]
I added a PR template now. Can you update the changelog?

**Comment by borkdude** [comment]
🙏

**Pull request merged**
